from lum import *
G='bibliotheque'
BG='img:route'
items_=[('pen','Surbrillances','124'),('mark','Marque-pages','18'),('note','Notes','86'),('link','Liens','23'),('book','Études','12'),('tag','Étiquettes','31'),('cal','Plans','3'),('heart','Méditations','40')]
screen('LL01-Bibliotheque','Ma bibliothèque',shell(
body(f'''<div class="btw" style="align-items:flex-end"><h1 class="h1">Ma bibliothèque</h1>{gbtn("search","Chercher")}</div>
<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px">{"".join(f'<a href="#" class="g" style="border-radius:20px;padding:12px 6px;display:flex;flex-direction:column;align-items:center;gap:6px;text-decoration:none;color:{TX};box-shadow:none">{ic(i,19)}{dot(n,20)}<span style="font:600 10.5px Geist">{t}</span></a>' for i,t,n in items_)}</div>
{micro("Récents")}
<div class="g" style="border-radius:24px;padding:0;overflow:hidden;display:flex;height:120px"><img src="{IMG['ecrit']}" alt="" style="width:120px;height:120px;object-fit:cover;object-position:top;filter:saturate(.15);background:#EDEBE6"><span class="col" style="padding:14px 16px;justify-content:center;gap:4px"><span class="micro">Note · Jean 3:16</span><span style="font:500 16px/1.4 Literata,serif">« Donner avant de recevoir. »</span><span class="gm" style="font-size:11px;color:{MU}">aujourd’hui · 07:40</span></span></div>
{card("".join(item(a,b,"",lead=lead(i),first=(k==0)) for k,(a,b,i) in enumerate([('Étude · L’amour dans Jean','modifiée hier · 12 versets','book'),('Surbrillance · Psaume 23:1','hier · 21:10','pen')])),pad="6px 18px",gap=0)}''',top_=60),'book',BG),G)
hls=[('Jean 3:16','auj.','#F1E7C6','Car Dieu a tant aimé le monde…'),('Psaume 23:1','hier','#DCE7DC','L’Éternel est mon berger…'),('Romains 8:28','14/09','#DCE2EC','Nous savons que toutes choses concourent…'),('Ésaïe 40:31','02/09','#EAD9DE','Ceux qui se confient en l’Éternel renouvellent leur force…')]
screen('LL02-Surbrillances','Surbrillances',shell(
top('#',chipc('Surbrillances · 124'),gbtn('filter','Filtrer'))+
body(f'''<div class="row" style="gap:8px">{"".join(f'<span class="row" style="gap:6px;height:32px;padding:0 12px;border-radius:16px;background:rgba(255,255,255,.6);font:600 12px Geist"><span style="width:14px;height:14px;border-radius:7px;background:{c};border:1px solid rgba(17,17,19,.1)"></span>{n}</span>' for n,c in [('jaune','#F1E7C6'),('vert','#DCE7DC'),('bleu','#DCE2EC'),('rose','#EAD9DE')])}</div>
{"".join(card(f'<span class="btw"><span class="gm" style="font-size:11.5px;color:{MU}">{r}</span><span style="font-size:11.5px;color:{MU}">{d}</span></span><span style="font:400 16px/1.5 Literata,serif;background:{c};border-radius:8px;padding:4px 8px;margin:0 -8px">{t}</span>',pad="12px 16px",gap=6) for r,d,c,t in hls)}''',top_=110,bottom=104),'book',BG),G)
screen('LL03-MarquePages','Marque-pages',shell(
top('#',chipc('Marque-pages'),None)+
body(f'''<div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px">{"".join(f'<a href="#" style="position:relative;height:150px;border-radius:6px 6px 0 0;background:{c};color:{"#FFFFFF" if c=="#111113" else TX};padding:14px 10px;box-sizing:border-box;text-decoration:none;display:flex;flex-direction:column;justify-content:space-between;clip-path:polygon(0 0,100% 0,100% 100%,50% 88%,0 100%)">{dot(n,24,"#FFFFFF" if c=="#111113" else TX)}<span style="font:600 12px Geist">{t}</span></a>' for n,t,c in [('3','Jean','#111113'),('23','Psaume','#E2E0DC'),('8','Romains','#E2E0DC')])}</div>
{card(f'<div class="btw">{micro("Marque-pages physiques")}{ic("qr",16)}</div><span style="font-size:14px">2 marque-pages QR glissés dans <b>BIB-2026-0001</b> : Jean 3 et Psaume 23.</span><span style="font-size:12px;color:{MU}">Scanner un marque-page ouvre le passage ici.</span>')}''',top_=110,bottom=104),'book',BG),G)
notes=[('Jean 3:16','01/10','Donner avant de recevoir','Lu avec le groupe ; parler de la mission.',['BIB-2026-0001','MIS-2026-0002']),('Psaume 23','30/09','Le berger','Prière pour les familles du lycée Ampère.',['Prière']),('Romains 8:28','14/09','Toutes choses','Relier à l’étude « Providence ».',[])]
screen('LL04-Notes','Notes',shell(
top('#',chipc('Notes · 86'),gbtn('plus','Nouvelle note'))+
body(f'''{search("Chercher dans les notes…")}
{"".join(card(f'<span class="btw"><span class="gm" style="font-size:11.5px;color:{MU}">{r}</span><span style="font-size:11.5px;color:{MU}">{d}</span></span><strong style="font:600 16px Geist">{t}</strong><span style="font:400 14.5px/1.5 Literata,serif;color:#33333A">{b}</span>'+('<div class="row" style="gap:6px;flex-wrap:wrap">'+"".join(f'<span class="pill">{x}</span>' for x in tg)+'</div>' if tg else ''),pad="14px 16px",gap=6) for r,d,t,b,tg in notes)}''',top_=110,bottom=104),'book',BG),G)
screen('LL05-Liens','Liens',shell(
top('#',chipc('Liens · 23'),gbtn('plus','Nouveau lien'))+
body("".join(f'<div class="g" style="border-radius:22px;padding:0;overflow:hidden;display:flex;height:96px;box-shadow:none"><img src="{IMG[i]}" alt="" style="width:96px;height:96px;object-fit:cover;filter:saturate(.15)"><span class="col" style="padding:12px 14px;justify-content:center;gap:2px"><span class="gm" style="font-size:11px;color:{MU}">{r}</span><strong style="font-size:14px">{t}</strong><span style="font-size:11.5px;color:{MU}">{u}</span></span></div>' for i,r,t,u in [('cours','Jean 3:16','Vidéo : l’amour de Dieu','youtube.com · BibleProject'),('plan','Jean 3','Article : la nouvelle naissance','topchretien.com'),('route','Psaume 23','Chant : le Seigneur est mon berger','partition PDF')]),top_=110,bottom=104),'book',BG),G)
def lines3(k):
    c='rgba(255,255,255,.3)' if k==0 else 'rgba(17,17,19,.12)'
    return ''.join(f'<i style="display:block;height:3px;border-radius:2px;width:{w}%;background:{c}"></i>' for w in (80,60,70))
studies=[('L’amour dans Jean','12 versets · modifiée hier','groupe'),('Providence','Romains 8 · 14/09',''),('Les psaumes du berger','4 psaumes · 02/09',''),('Préparer la mission','6 versets · 3 réalités','mission')]
screen('LL06-Etudes','Études',shell(
top('#',chipc('Études · 12'),gbtn('plus','Nouvelle étude'))+
body(f'''<div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px">{"".join(f'<a href="#" class="g" style="border-radius:22px;padding:14px;height:150px;box-sizing:border-box;display:flex;flex-direction:column;justify-content:space-between;text-decoration:none;color:{TX};box-shadow:none;{"background:#111113;color:#FFFFFF;border-color:#111113" if k==0 else ""}"><span class="col" style="gap:5px">{lines3(k)}</span><span class="col"><strong style="font:600 15px Literata,serif">{t}</strong><span style="font-size:11.5px;opacity:.6">{s}</span></span></a>' for k,(t,s,c) in enumerate(studies))}</div>''',top_=110,bottom=104),'book',BG),G)
screen('LL07-EditeurEtude','Éditeur d’étude',shell(
top('#',chipc('L’amour dans Jean'),gbtn('share','Partager'))+
body(f'''<div class="row" style="gap:6px">{"".join(f'<span style="width:36px;height:36px;border-radius:12px;background:rgba(255,255,255,.6);display:flex;align-items:center;justify-content:center;font:700 13px Geist">{x}</span>' for x in ['B','I','H','•','“'])}<span style="flex:1"></span><span class="pill on">+ verset</span><span class="pill">+ réalité</span></div>
<h2 style="margin:4px 0 0;font:600 24px/1.2 Literata,serif">1. Un amour qui se donne</h2>
<div style="border-left:3px solid #111113;padding:4px 0 4px 14px"><span class="gm" style="font-size:11.5px;color:{MU}">Jean 3:16 · LSG</span><p style="margin:4px 0 0;font:400 16px/1.55 Literata,serif">Car Dieu a tant aimé le monde qu’il a donné son Fils unique…</p></div>
<p style="margin:0;font:400 16px/1.65 Literata,serif">Le verbe <b>ἀγαπάω (G25)</b> désigne un amour de choix. Pour la mission de rentrée, ce verset sera imprimé sur le marque-page offert avec chaque Bible.</p>
<div class="g" style="border-radius:20px;padding:12px 14px;display:flex;align-items:center;gap:12px;box-shadow:none">{lead("flag")}<span class="col"><span class="micro">Réalité liée</span><strong style="font-size:14px">MIS-2026-0002 · 1000 Bibles</strong></span></div>''',top_=110,bottom=30),None,BG),G)
screen('LL08-Etiquettes','Étiquettes',shell(
top('#',chipc('Étiquettes · 31'),gbtn('plus','Nouvelle étiquette'))+
body(f'''<div class="row" style="gap:6px;flex-wrap:wrap">{"".join(f'<span class="pill{" on" if k==0 else ""}">{t}</span>' for k,t in enumerate(['Mission · 14','Prière · 22','Famille · 9','Étude · 31','Lycée · 6']))}</div>
<div class="col" style="gap:4px"><span class="micro">Étiquette</span><h1 class="h1">Mission</h1><span class="sub">Une étiquette relie tout : la Bible et le réel.</span></div>
{card("".join(item(a,b,f'<span style="font:600 9.5px Geist Mono;letter-spacing:.06em;text-transform:uppercase;color:{MU}">{k_}</span>',lead=lead(i),first=(k==0)) for k,(a,b,i,k_) in enumerate([('Jean 3:16','verset surligné','book','bible'),('Donner avant de recevoir','note · 01/10','note','note'),('MIS-2026-0002','1000 Bibles','flag','réalité'),('DOC-2026-0213','bon de livraison','paper','réalité')])),pad="6px 18px",gap=0)}''',top_=110,bottom=104),'book',BG),G)
plans=[('plan','BibleProject · la Bible en 1 an',58,'Jean 3 – 4','214'),('elie','Calendrier de Spurgeon',75,'Psaume 23','matin'),('p1','Les Évangiles en 90 jours',13,'Marc 4','12')]
screen('LL09-Plans','Plans de lecture',shell(
top('#',chipc('Plans de lecture'),None)+
body(f'''{seg(["Mes plans","Découvrir"],0)}
{"".join(f'<div class="g" style="border-radius:24px;padding:0;overflow:hidden;display:flex;box-shadow:none"><img src="{IMG[i]}" alt="" style="width:100px;height:116px;object-fit:cover;filter:saturate(.15)"><span class="col" style="flex:1;padding:12px 14px;gap:6px;justify-content:center"><strong style="font-size:14px">{t}</strong><span style="font-size:12px;color:{MU}">aujourd’hui : {d}</span>{bar(p,TX,4)}</span></div>' for i,t,p,d,j in plans)}''',top_=110,bottom=104),'book',BG),G)
screen('LL10-Plan','Plan du jour',shell(
top('#',chipc('BibleProject'),None)+
body(f'''<div class="row" style="align-items:baseline;gap:6px"><span class="micro">Jour</span>{dot("214",64)}<span class="dot" style="font-size:24px;color:rgba(17,17,19,.25)">/365</span></div>
<div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:6px">{"".join(f'<span class="col" style="align-items:center;gap:4px"><span style="font:600 10.5px Geist Mono;color:{MU}">{d}</span><span style="width:34px;height:34px;border-radius:17px;display:flex;align-items:center;justify-content:center;{"background:#111113;color:#FFFFFF" if i<3 else "border:2px solid #111113" if i==3 else "background:rgba(255,255,255,.6)"}">{ic("check",14,"#FFFFFF",2.4) if i<3 else ""}</span></span>' for i,d in enumerate('LMMJVSD'))}</div>
{card("".join(f'<div class="row" style="padding:10px 0;gap:12px;{"" if k==0 else "border-top:1px solid "+LINE}"><span style="width:24px;height:24px;border-radius:12px;{"background:#111113" if d else "border:2px solid rgba(17,17,19,.25)"};display:flex;align-items:center;justify-content:center;flex:none">{ic("check",13,"#FFFFFF",2.4) if d else ""}</span><span class="col" style="flex:1"><strong style="font-size:14.5px">{t}</strong><span style="font-size:12px;color:{MU}">{s}</span></span></div>' for k,(t,s,d) in enumerate([('Jean 3','lu · 07:40',True),('Jean 4','5 min',False),('Vidéo : Jean 1-12','8 min',False)])),pad="6px 18px",gap=0)}
<a href="#" class="btn k" style="margin-top:auto">Lire Jean 4</a>''',top_=110,bottom=30),None,BG),G)
screen('LL12-Meditation','Méditation',shell(
top('#',chipc('Le berger · 2 / 6'),gbtn('list','Collection'))+
f'''<div style="position:absolute;left:16px;right:16px;top:110px;height:400px;border-radius:32px;overflow:hidden"><img src="{IMG['route']}" alt="" style="width:100%;height:100%;object-fit:cover;filter:saturate(.12) brightness(.8)"><div style="position:absolute;inset:0;background:linear-gradient(180deg,rgba(17,17,19,.1),rgba(17,17,19,.7))"></div><div style="position:absolute;left:22px;right:22px;bottom:24px;color:#FFFFFF;display:flex;flex-direction:column;gap:12px"><span style="font:500 25px/1.35 Literata,serif">« Il me fait reposer dans de verts pâturages. »</span><span style="font-size:14px;opacity:.8">Respirez. Où sont, aujourd’hui, vos « verts pâturages » ?</span></div></div>'''+
body(f'''<div class="g" style="height:110px;border-radius:22px;padding:14px 16px;color:{MU};font-size:14.5px;box-shadow:none">Ce que je retiens…</div><div class="row" style="gap:10px"><a href="#" class="btn w" style="flex:1">Précédent</a><a href="#" class="btn k" style="flex:1">Suivant</a></div>''',top_=530,bottom=30),None,'plain'),G)
